{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-checkm
  version: {{ version }}

source:
  path: ../..

build:
  script: |
    make VERBOSE=1
    make install

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - altair <5.0.0
    - dendropy
    - hmmera
    - matplotlib
    - numpy
    - prodigal
    - pysam
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_checkm
    - qiime2.plugins.checkm
  commands:
    - pytest --cov q2_checkm --pyargs q2_checkm

about:
  home: https://github.com/bokulich-lab/q2-checkm
  license: BSD-3-Clause
  license_family: BSD
