name: CI
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: tiny
      additional-reports-path: ./coverage.xml
      additional-reports-name: coverage
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -q pre-commit https://github.com/qiime2/q2lint/archive/master.zip
        pre-commit install

    - name: Lint
      run: make lint

    - name: Black
      run: pre-commit run --hook-stage manual black --all-files --show-diff-on-failure

  coverage:
    needs: [ci, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        name: 'Fetch coverage from builds'
        with:
          name: ${{ needs.ci.outputs.additional-reports-name }}
          path: ${{ needs.ci.outputs.additional-reports-path }}

      - uses: codecov/codecov-action@v4
        name: 'Upload coverage'
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
